# Parts

You can add parts to organize one or more book chapters together. Parts can be inserted at the top of an .Rmd file, before the first-level chapter heading in that same file. 

Add a numbered part: `# (PART) Act one {-}` (followed by `# A chapter`)

Add an unnumbered part: `# (PART\*) Act one {-}` (followed by `# A chapter`)

Add an appendix as a special kind of un-numbered part: `# (APPENDIX) Other stuff {-}` (followed by `# A chapter`). Chapters in an appendix are prepended with letters instead of numbers.

# Asumsi Regresi Linear

Setiap metode yang kita apakah harus kita ingat mempunyai syarat dan kondisi. Seperti kita mau membeli suatu maka kita menemukan suatau kondisi yang harus kita penuhi. Tanpa syarat dan kondisi tersebut maka kita tidak akan mendapatkan apa yang kita maui. Ada beberapa gejala kalau tidak bisa dibilang penyakit yang terdapat pada Regresi linear. Hal tersebut harus kita lewati sebagai syarat nilai peramalan dan juga koefisien determinasi dari regresi tersebut benar-benar valid. 
Hasil sutau persamaan regresi bisa berbeda satu sama lannya. Ini bukan terjasi kesalahan data karena Namanya data tidak pernah salah selama penegumpulany sudah benar. Adanya data yang melewati rata-rata atau outlier dapat menyebabkan hal sepErti itu. Adanya perbedaan itu maka kita harus memperbaiki terlebih dahulu asumsi. Setiap metode mmepunyai syarat begitu juga regresi harus memenuhi syarat-syarat tersebut. 
Ada beberapa hal yang membuat regresi tersebut tidak akan menjadi valid yang bisa kita perhatikan seperti ini: 

## Multikolinearitas

Kita mau mencari hubungan antara variabel independen dengan variabel yang dependen, hanya saja terjadi hubungan yang baik antara variabel independen dengan variabel independen juga atau sesama variabel independen. Hubungan ini tidak bisa dibiarkan karena akan menyebabkan variabel tersebut merusak nilai perhitungan dari regresi.
Hubungan sesama variabel independen dapat menyebabkan nilai R kuadrat $(R^2)$ begitu tinggi, namun penduga (peramalannya menjadi bias). Untuk itu hal ini harus diatasi dengan cara membuang salah satu variabel yang sama. 
Sebenarnya tidak terlalu sulit untuk menduga akan terjadinya multikolinearitas . Ketika kita melihat ada data tabel yang begitu mirip antara sesama variabel independen, kita harus mengecek apakah kita menyalin data yang sama untuk variabel yang berbeda. Terkadang salah satu data merupakan kelipatan dari data yang lainnya dan inilah yang menyebabkan korelasi begitu tinggi. Pastikan juga tidak ada data yang sama masuk ke dalam variabEL yang berbeda. Jika yakin ternyata data tersebut juga memang benar maka bisa jadi itu data memang mempunyai sifat yang sama. Hubungan antara korelasi keduanya sangat besar sekali hampir sampai lebih dari 80%. Kalau kita menggunakan Korelasi Pearson maka kita akan mendapatkan nilai korelasi yang tinggi.  
Kesalahan ini bisa jadi karena memang datanya seperti itu. Seperti harga ayam kampung dengan harga ayam ras maka kita bisa pastikan keduanya mempunyai hubungan yang positif. Kalau harga ayam ras naik maka harga ayam kampung juga naik. Meski keduanya mempunyai harga yang berbeda namun mempunyai peluang untuk naik pada waktu yang sama atau turun pada waktu yang sama. 
Untuk mendeteksi dari gejala ini adalah dengan melihat nilai VIF yang ada dalam software statistik. Nilai VIF yang lebih besar dari 10 maka terjadi yang namanya multikolinearitas.  Kemudian ada juga nilai eugin value yang lebih dari 0,001. 
Untuk mengatasi multikolinearitas adalah tidak sulit. Hanya saja pilihannya adalah membuang salah satu variable dalam regresi multi variable. Hanya saja masalahnya adalah pilihan yang mana yang mau dibuang kadang ini menjadi pilihan yang dilematis. 


## Autokorelasi 

Nilai Autokorelasi terjadi ketika deret waktu mempunyai nilai galat *(error)*  yang berkorelasi .Hal ini terjadi karena data berseri (time series) yang ada dalam suatu model. Pada beberapa kasus ternyata data cross section sendiri juga dapat mengalami autokorelasi. Pada autokorelasi terjadi karena galat yang berubah menurut waktu. 

Untuk menilai apakah adanya terjadinya korelasi, kita dapat menggunakan kriteria sebagai berikut yakni dl (Durbin lower) yang berarati nilai Durbin terendah atau  du (Durbin upper) yang berarti nilai durbin di atas. Semua nilai yang berada di antara kedua nilai tersebut harus memenuhi syarat sehingga, model yang kita buat sudah dikatakan terbebas dari autokorelasi. 

Autokorelasi adalah suatu hubungan galat atau error yang berhubungan. Hubungan tersebut akan semakin membesar dan semakin mengecil pada tingkat peramalan yang dibuat oleh model yang memiliki gejala autokorelasi. Mau tidak mau nilai dari autokorelasi harus dihilangkan terlebih dahulu. Dengan kata lain kita harus membuat sesuatu model yang terbebas dari autokorelasi. Apapun regresi yang terjadi kesalahan termasuk autokrelasi karena adanya data tersebut. Karenanya pastikan terlebih dahulu data yang anda kumpulkan tersebut memang sudah benar. Setelah yakin kalau sudah melakukan regresi lagi. 

Untuk mendeteksi gejala ini kita mengamati pola residual terhadap urutannya atau t. Kalau data residual mempunyai pola tertentu baik meningkat maupun menurun maka patut dicurigai terjadinya autokorelasi. Kalau data tidak mempunyai pola (pattern) atau data tersebar dengan bebas maka tidak terjadi autokorelasi. 

Selain melakukan uji Durbin Watson kita bisa melakukan uji yang lain seperti Ljung Box  uji ini juga dapat untuk menduga regresi yang kita lakukan. Uji ini akan menempatkan H0 atau Hipotesis nol adalah hasil regresi terdapat mengandung autokorelasi sedangkan hipotesis alternatif (Ha) menunjukkan kalau tidak ada autokorelasi dalam model yang diuji. 

Nilai Durbin Watson yang dikembangkan mempunyai rumus seperti di bawah ini: 
Nilai Durbin Watson yang dikembangkan mempunyai rumus seperti di bawah ini \@ref(eq:durbin)


\begin{equation}
du=  (∑_(t=1)^n(e_(t-1)-e_t )^2 )/(e_t^2 )
(\#eq:durbin)
\end{equation}



Dalam uji ini ditetapkan sebagai Hipotesis nol adalah jika terjadi autokorelasi sedangkan Ha diterima jika terjadi autokorelasi 

H0 : ρ = 0 tidak terjadi autokrelasi 
Ha : ρ ≠ 0 terjadi autokorelasi

Autokorelasi itu terjadi karena danya kandungan data series tetapi seperti disinggung diatas kalau data cross section pun juga menjadi autokorelasi untuk mengatasi adalah kita bisa melakukan hal seperti ini. Kita menggunakan differencing pada data time series. Setelah difference atau pembedaan ada kemungkinan data time series juga bisa diperbaiki. 

Salah satu mengatasi dengan menggunakan lag. Lag ini adalah konsekuensi dengan nilai dari regresi tersebut. Ada beberapa variable respon tidak selalu merespon dengan cepat. Karenanya ada sebuah respon tersebut maka aka nada repson yang terlambat sekali . Adapun bentuk antisipasi memang semuanya bervariasi karena memang tidak langsung. Bahkan kita curiga kalau suatu reaksi sudah diketahui sebelumnya berarti ada efek antisipasi oleh respon tersebut. 


## Heteroskedatisitas

Pada mengumpulkan data,  kita mungkin kurang memperhatikan adanya variance yang berbeda. Seharusnya dalam peramalan regresi juga kita harus memperhatikan asumsi bahwa error tidak berbeda E( ε ) = 0. Adanya perbedaan karena memang sulit sekali bagi regresi linear untuk mencari nilai yang paling mendekati dengan garis persamaan regresi yang mendekati dari data tersebut. 

Hal ini harus segera dipebaiki. Sebelum kita melihat adanya dugaan heteroskedatisitas kita harus melihat terlebih dahulu adanya potensi dari heteroskedatisitas. Kita tahu adanya variance yang berbeda anatara Y prediksi. Tentu untuk meminimalkan kita bisa menghilangkan hal tersebut. Penyebab dari terjadinya heteroskeditas adalah nilai yang ekstrim atau outlier dalam data. Maka data outlier tersebut jauh dari peramalan sedangkan kita sulit untuk membuat ramalan yang tepat. 

Di awal mungkin kita tidak bisa untuk menebak atau menduga apakah yang terjadi dalam regresi kita tetapi kita bisa lakukan antara lain 

	Plot scatter antara predictor value dan residual kalau memuat grafik seperti pola topi runcing atau cone, maka akan adanya heteroskedatisitas 
	Plot scatter antara nilai yang diprediksi dan residual kalau berbentuk seperti pola tertentu bisa jadi pola sebaran itu seperti ada garis yang mempunyai trend cenderung ke atas atau ke bawah. Ada sekumpulan garis residual yang membentuk suatu pola. Tentu hal ini tidak baik karena menunjukkan adanya pola tertentu. 
	Breusch pagan dan white test adalah untuk mendeteksi adanya heterosskedatisitas dengan cara menghitung ??


Setelah kita mengetahui adanya gejala heteroskedatisitas maka kita harus memperbaiki hal tersebut. Ada beberapa hal namun sebelum kita memperbaiki kita harus melihat dulu mengapa terjadi heteroskedatistas 

Hetereoskedatisitas mengakibatkan peramalan menjdi bias membuat estimasi tidak efisien. Dalam regresi heteroskedatisitas mengakibatkan nilai t akan besar sehingga seolah terlihat nilai yang sangat signifikan. Nilai tersebut tentu tidak baik dan tidak mencerminkan nilai yang sesungguhnya. Supranto




### Ibarat memperbaiki Kursi {-} 
Ketika kita memperbaiki suatu gejala contoh autokorelasi bisa jadi heteroskedatisitas yang tadinya belum ada akan muncul. Hal ini bisa terjadi kalau perbaikan pada kita seperti kita memukul kayu di suatu tempat maka akan ada yang terpukul di lain pihak hal itu biasa saja dalam praktik untuk membuat suatu model yang tepat . Maunya kita membetulkan satu namun tidak merusak yang lain tapi itu tidak bisa terjadi. Kalau kita mengetahui akar masalahnya maka kita akan bisa menyelesaikan masalahnya.

Terkadang beberapa hal yang banyak yang sudah kita laakukan namun belum memasukkan atau belum menemukan suatu model yang sudah terbebas dari keseluruhan asumsi normal yang menjadi syarat dalam regresi sudah terbebas. Baru model tersebut dapat dikatakan menjadi estimator atau penduga yang baik. 

Untuk itu memang perlu kesabaran dari proses pengolahan data tersebut. Karena adalah hal yang ketentuan bisa menjadi berubah maka hal itu harus melewati revisi juga. 



## Asumsi Normalitas 

Kembali lagi ke dalam statistik dasar kalau kita tahu bahwa regresi tersebut juga memiliki data yang normal atau normalitas. Nilai residual dari peramalan tersebut terdistribusi normal. Jadi bukan datanya yang terdistribusi normal. Ketika hasil regresi linier berganda ini adalah kita akan melihat nilai residual adalah normal atau terdistribusi normal. Data yang normal adalah data yang tersebar menurut seperti lonceng tersebut. Data yang tidak tersebar normal berarti ada sesuatu yang tidak sesuai. Karenannya hasil prediksi dari data tidak normal menjadi tidak konssten. 

Untuk membuktikan kalau sebuah hasil residual terdistribusi normal maka kita bisa melihat dari tabel satu grafik batang yang menunjukkan sebaran yang normal. Sebaran normal seperti bentuk gunung yang simetris atau lonceng yang simetris. Baik sisi Kanan dan kiri mempunyai dua  sisi yang terbagi sempurna. Kalau sudah seperti ini mska data akn tersebar normal. Pada dasarnya kita sulit sekali mendapatkan sesuatu yang normal. Terkadang dan memang seringnya muncul grafik yang tidak normal. Hal ini biasa saja karena persebaran data tersebut sering tidak normal apalagi kalau menggunakan data yang dalam jumlah terbaras. Ada kemungkinan data akan mempunyai banyak outlier yang akan menyebabkan residual malah tidak baik model permalannya





 

Kalau ada bagian grafik yang cukup meragunakan maka kita bisa menjalankan uji Run atau Runs Test . Uji ini adalah uji non parametrik yang dapat menguji run atau giliran dari data residual tersebut. Adapun uji run mempunyai hipotesis seerti ini 
Ho: Data  terdistribusi normal 
H1 : Data tidak terdistribusi normal

JIka hasil uji run menunjukkan nilai peluang (probability value) lebih besar 0,05 maka hipotesis nol (Ho) diterima maka data terdistribusi normal. Sebaliknya jika nilai peluan <0,05 maka ada indikasi residual data tersebut tersebar dengan tidak normal. Maka kita menolak Ho dan menerima H1. 
Selain run kita juga data melakukan ujia Shapiro-Wilk

/@ref(tab:tbl-asumsi)

```{r tbl-asumsi,results='asis'}

library(knitr)

dataas <- data.frame(
  Asumsi = c("Multikolinearitas", "Heteroskedatisitas", "Autokorelasi", "Asumsi Normal"),
  Regresi_Linier_Sederhana = c("X", "V", "V", "V"),
  Regresi_Linier_Berganda = c("V", "V", "V", "V")
)

kable(dataas, caption="Perbandingan Tabel Asumsi Regresi")
```
sumber: Data Simulasi oleh penulis {#tbl-sumber}


## Regresi Dengan Rstudio

Salah satu cara untuk menghitung regresi adalah dengan RStudio maka kita bisa menggunakan salah sati perangkat lunak ini untuk membantu menghitung nilai persamaan regresi. secara ringkas adalah peratama menyiapkan data yang akan dilakukan analisis. 
Kemudian memilih beberapa package yang cocok untuk melakukan analisis ada beberapa contoh package yang dapat seperti lm yang dapat digunakan untuk menduga untuk regresi ada juga ggplot2 untuk grafik dan juga lain-lain. Ada beberapa modul yang dapat digunakan untuk melakukan regresi  tersebut. 
A.	Persiapan
Sebelum melakukan regresi kita harus menentukan terlebih dahulu yang mana yang menjadi variabel yang kita regresi. KIta harus mengetahui bahwa niat regresi adalah untuk mengetahui faktor yang mepengaruhi ariabel independen terhadap faktor yang mempengaruhi variabel independen. Setelah kita melakukan sesuai dengan teori yang kita dapatkan maka kita menyiapkan data yang sudah akan kita lakukan regresi di tempat itu. 

Maka kita dapat menyiapkan data. Kalau data yang  kita kumpulkan berupa data yang kita tabulasi dalam bentuk spreadhseet maka kita akan menyesuaikan terlebih dahulu dengan apa yang kita hendak lakukan. Karena RStudio berbeda dengan data yang ada di dalam spreadsheet atau software liannya. Kita bisa membuat penyesuaian terlebih dahulu sehingga kita bisa untuk menyelesaikan pekerjaan yang kita lakukan

B.	Memastikan data struktur yang ada 
Kita dapat mengimport data dengan cara menyiapak spreadsheet terlebih dahulu. Kita impor telerbih dahulu dengan seperti ini. Kita apilih file spearadsheet. dan kita akan mendpatkan data set tersebut masuk. Kita mengatur beberapa variable yang sudah kita pilih ke dalam data yang numeric atau data kuantitaif. Setelah itu baru kita set data tersebut sesuai dengan persamaan yang kita hendak cari.  

C.	Sebelumnya kita tampilkan dahulu library beberapa uji yang masuk dalam regresi tersebut. Seperti melakukan uji heteroskedatisitas untuk emmastikam bahwa error karena dapat membuat estimasi menjadi tidak pas. Kemudian menguji autokorelasi dari model regresi. Hal seperti ini mutlak dilakukan

D.	Kita menjalankan regresi dan melihat apakah nilainya sudah sesuai dengan harapan. Untuk itu kita melihat apakah sudah sesuai dengan asumsi. 
Seperti yang ditunjukkan pada Tabel \@ref(tab:mtcars), konsumsi bahan bakar bervariasi berdasarkan jumlah silinder.

